name = "MuJoCoWarpInterface"
uuid = "a2868a16-2106-452a-9d7a-deb84d0ae73b"
authors = ["kurorodev <danyakud13@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
